name: e2e tests

on: [pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - run:
          sudo apt-get update && sudo apt-get install -y python3-pip git && sudo
          pip3 install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install a Yeti prod deployment
        run: git clone https://github.com/yeti-platform/yeti-docker && cd yeti-docker/prod && ./init.sh
      - name: Install Python dependencies
        run: poetry install --no-root
      - name: e2e testing
        run: |
          poetry run python -m unittest tests/e2e.py
